# Generated by Django 5.0.14 on 2026-06-01 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('symbol', models.CharField(help_text='e.g., AAPL or SWDA.MI', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('Stock', 'Stock'), ('ETF', 'ETF')], default='Stock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('sentiment_score', models.FloatField(blank=True, help_text='Between -1.0 and +1.0', null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Neutrale', 'Neutrale'), ('Negativo', 'Negativo')], max_length=15, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='core_newsar_asset_i_714d65_idx')],
                'unique_together': {('asset', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.asset')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='core_priced_asset_i_35e0bc_idx')],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
