# Generated by Django 5.0.14 on 2026-06-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15)),
                ('avg_sentiment', models.FloatField(help_text='Rolling average sentiment that triggered the alert.')),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.asset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'level', 'created_at'], name='core_alert_asset_i_753397_idx')],
            },
        ),
    ]
