# Generated by Django 5.0.14 on 2026-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Theme category (cold-start keyword vote; refined by later NLP stages).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='forward_impact',
            field=models.JSONField(blank=True, help_text='Forward % return at 1/3/7d from publish — supervision signal for self-calibration.', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_relevant',
            field=models.BooleanField(blank=True, help_text='Whether the category is price-relevant; null = unknown (not yet decided).', null=True),
        ),
    ]
