# Generated by Django 5.0.14 on 2026-06-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsarticle_category_newsarticle_forward_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='source_tier',
            field=models.CharField(blank=True, db_index=True, help_text='Source quality tier (premium|quality|unverified) from the curated registry.', max_length=12, null=True),
        ),
    ]
