# Generated by Django 5.0.14 on 2026-06-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsarticle_source_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetScore',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='core.asset')),
                ('score', models.FloatField(db_index=True, default=0.0, help_text='Composite 0–100 opportunity score.')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('components', models.JSONField(default=dict, help_text='Normalized sub-scores (-1..1).')),
                ('n_articles', models.PositiveIntegerField(default=0)),
                ('low_news', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
