# Generated by Django 5.0.14 on 2026-06-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assetscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initial_capital', models.FloatField(default=0.0)),
                ('cash', models.FloatField(default=0.0, help_text='Uninvested virtual cash.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('value', models.FloatField(help_text='quantity × price (cash moved).')),
                ('reason', models.CharField(help_text='Signal that triggered it (buy/sentiment/stop_loss).', max_length=20)),
                ('realized_pnl', models.FloatField(blank=True, help_text='Profit/loss closed by a SELL (null for BUY).', null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_trades', to='core.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.portfolio')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['portfolio', 'executed_at'], name='core_papert_portfol_7195dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cash', models.FloatField()),
                ('holdings_value', models.FloatField(help_text='Mark-to-market value of all open positions.')),
                ('total_value', models.FloatField(help_text='cash + holdings_value (the equity).')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.portfolio')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['portfolio', 'timestamp'], name='core_portfo_portfol_2c3a0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('avg_entry_price', models.FloatField(default=0.0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core.portfolio')),
            ],
            options={
                'ordering': ['asset_id'],
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
